<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1">

<meta name="author" content="Martin Mächler" />


<title>Rounding to Decimal Digits in Binary</title>



<style type="text/css">code{white-space: pre;}</style>
<style type="text/css" data-origin="pandoc">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>



<style type="text/css">

body {
background-color: #fff;
margin: 1em auto;
max-width: 700px;
overflow: visible;
padding-left: 2em;
padding-right: 2em;
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size: 14px;
line-height: 1.35;
}
#header {
text-align: left; 
}
#TOC {
clear: both;
margin: 0 0 10px 10px;
padding: 4px;
width: 400px;
border: 1px solid #CCCCCC;
border-radius: 5px;
background-color: #f6f6f6;
font-size: 13px;
line-height: 1.3;
}
#TOC .toctitle {
font-weight: bold;
font-size: 15px;
margin-left: 5px;
}
#TOC ul {
padding-left: 40px;
margin-left: -1.5em;
margin-top: 5px;
margin-bottom: 5px;
}
#TOC ul ul {
margin-left: -2em;
}
#TOC li {
line-height: 16px;
}
table {
margin: 1em auto;
border-width: 1px;
border-color: #DDDDDD;
border-style: outset;
border-collapse: collapse;
}
table th {
border-width: 2px;
padding: 5px;
border-style: inset;
}
table td {
border-width: 1px;
border-style: inset;
line-height: 18px;
padding: 5px 5px;
}
table, table th, table td {
border-left-style: none;
border-right-style: none;
}
table thead, table tr.even {
background-color: #f7f7f7;
}
p {
margin: 0.5em 0;
}
blockquote {
background-color: #f6f6f6;
padding: 0.25em 0.75em;
}
hr {
border-style: solid;
border: none;
border-top: 1px solid #777;
margin: 28px 0;
}
dl {
margin-left: 0;
}
dl dd {
margin-bottom: 13px;
margin-left: 13px;
}
dl dt {
font-weight: bold;
}
ul {
margin-top: 0;
}
ul li {
list-style: circle outside;
}
ul ul {
margin-bottom: 0;
}
pre, code {
background-color: #f7f7f7;
border-radius: 3px;
color: #333;
}
pre {
overflow-x: auto; 

border-radius: 3px;
margin: 5px 0px 10px 0px;
padding: 10px;
}
pre:not([class]) {
background-color: white; 
border: #CCCCCC 1px solid; 
}

pre:not([class]) code {
color: #444;
background-color: white;
}
code {
font-family: Menlo, monospace; 
font-size: 90%; 
}
p > code, li > code {
padding: 2px 0px;
}
div.figure {
text-align: center;
}
img { 
background-color: #FFFFFF;
padding: 2px;

border-radius: 3px;
border: none; 
margin: 0 5px;
max-width: 100%; 
text-align: center; 
}
h1 {
margin-top: 0;
font-size: 35px;
line-height: 40px;
}
h2 {
border-bottom: none; 
padding-top: 10px;
padding-bottom: 2px;
font-size: 145%;
}
h3 {
border-bottom: none; 
padding-top: 10px;
font-size: 120%;
}
h4 {
border-bottom: none; 
margin-left: 4px; 
font-size: 105%;
}
h5, h6 {
border-bottom: none; 
font-size: 105%;
}
a {
color: #0033dd;
text-decoration: none;
}
a:hover {
color: #6666ff; }
a:visited {
color: #800080; }
a:visited:hover {
color: #BB00BB; }
a[href^="http:"] {
text-decoration: underline; }
a[href^="https:"] {
text-decoration: underline; }

code > span.kw { color: #555; font-weight: bold; } 
code > span.dt { color: #902000; } 
code > span.dv { color: #40a070; } 
code > span.bn { color: #d14; } 
code > span.fl { color: #d14; } 
code > span.ch { color: #d14; } 
code > span.st { color: #d14; } 
code > span.co { color: #888888; font-style: italic; } 
code > span.ot { color: #007020; } 
code > span.al { color: #ff0000; font-weight: bold; } 
code > span.fu { color: #900; font-weight: bold; } 
code > span.er { color: #a61717; background-color: #e3d2d2; } 
</style>




</head>

<body>




<h1 class="title toc-ignore">Rounding to Decimal Digits in Binary</h1>
<h4 class="author">Martin Mächler</h4>
<h4 class="date">1st version: Jan. 2020; rendered on 2020-01-15</h4>



<div id="intro" class="section level2">
<h2>Intro</h2>
<p>In R (and its predecessors S and S+), we have always known and often used <code>round(x, digits)</code> to round a numeric (or complex) vector of numbers <code>x</code> to <code>digits</code> decimals after the (decimal) point. However, not many R users (nor scientists for that matter) have been aware of the fact that such rounding is not trivial because our computers use binary (<em>base</em> <strong>2</strong>) arithmetic and we are rounding to decimal digits, aka decimals, i.e., in <em>base</em> <strong>10</strong>.</p>
<p>On the topic of floating point computation, we have had the <em>most</em> frequently asked question (FAQ) about R, the infamous <a href="https://cran.r-project.org/doc/FAQ/R-FAQ.html#Why-doesn_0027t-R-think-these-numbers-are-equal_003f">R FAQ 7.31</a>, and in 2017, Romain François even created an R package <a href="https://github.com/ThinkR-open/seven31" title="seven31">seven31</a> (not on CRAN) to help useRs exploring what we say in the FAQ.</p>
<!-- ~/R/MM/NUMERICS/round-even-odd.R  -->
<p>Recently, there has been an official R bug report (on R’s bugzilla), <code>PR#17668</code> <a href="https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17668" class="uri">https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17668</a> with summary title <strong>Artificial numerical error in <code>round()</code> causing round to even to fail</strong>.</p>
<p>Adam Wheeler started with a shorter version (just using digits = 1,2,..,8) of the following examples and his own remarks about correctness:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" title="1"><span class="kw">options</span>(<span class="dt">digits =</span> <span class="dv">15</span>)</a>
<a class="sourceLine" id="cb1-2" title="2">                         <span class="co"># R &lt;= 3.6.x :</span></a>
<a class="sourceLine" id="cb1-3" title="3"><span class="kw">round</span>(<span class="fl">55.5</span>, <span class="dv">0</span>)           <span class="co"># 56 &lt;- correct</span></a></code></pre></div>
<pre><code>## [1] 56</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" title="1"><span class="kw">round</span>(<span class="fl">55.55</span>, <span class="dv">1</span>)          <span class="co"># 55.5</span></a></code></pre></div>
<pre><code>## [1] 55.5</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" title="1"><span class="kw">round</span>(<span class="fl">55.555</span>, <span class="dv">2</span>)         <span class="co"># 55.55</span></a></code></pre></div>
<pre><code>## [1] 55.55</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" title="1"><span class="kw">round</span>(<span class="fl">55.5555</span>, <span class="dv">3</span>)        <span class="co"># 55.556 &lt;- correct</span></a></code></pre></div>
<pre><code>## [1] 55.556</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" title="1"><span class="kw">round</span>(<span class="fl">55.55555</span>, <span class="dv">4</span>)       <span class="co"># 55.5555</span></a></code></pre></div>
<pre><code>## [1] 55.5555</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" title="1"><span class="kw">round</span>(<span class="fl">55.555555</span>, <span class="dv">5</span>)      <span class="co"># 55.55555</span></a></code></pre></div>
<pre><code>## [1] 55.55555</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" title="1"><span class="kw">round</span>(<span class="fl">55.5555555</span>, <span class="dv">6</span>)     <span class="co"># 55.555555</span></a></code></pre></div>
<pre><code>## [1] 55.555555</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" title="1"><span class="kw">round</span>(<span class="fl">55.55555555</span>, <span class="dv">7</span>)    <span class="co"># 55.5555556 &lt;- correct</span></a></code></pre></div>
<pre><code>## [1] 55.5555556</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" title="1"><span class="kw">round</span>(<span class="fl">55.555555555</span>, <span class="dv">8</span>)   <span class="co"># 55.55555555</span></a></code></pre></div>
<pre><code>## [1] 55.55555555</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" title="1"><span class="kw">round</span>(<span class="fl">55.5555555555</span>, <span class="dv">9</span>)  <span class="co"># 55.555555555</span></a></code></pre></div>
<pre><code>## [1] 55.555555555</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" title="1"><span class="kw">round</span>(<span class="fl">55.55555555555</span>,<span class="dv">10</span>) <span class="co"># 55.5555555556 &lt;- correct</span></a></code></pre></div>
<pre><code>## [1] 55.5555555556</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" title="1"><span class="kw">round</span>(<span class="fl">55.555555555555</span>,<span class="dv">11</span>)<span class="co"># 55.55555555556 &lt;- correct</span></a></code></pre></div>
<pre><code>## [1] 55.55555555556</code></pre>
<p>Whereas the exact result of the R code above currently depends on your version of R, our <code>round</code> package’s <code>roundX(x, dig, version = &quot;r1.C&quot;)</code> provides these, using the same C source code as R 3.6.2 (note I have adopted the convention to use “r<n>.C” for round()ing versions where R calls package C code):</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" title="1"><span class="kw">require</span>(round)</a></code></pre></div>
<pre><code>## Loading required package: round</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" title="1"><span class="kw">roundX</span>(<span class="fl">55.5</span>, <span class="dv">0</span>, <span class="st">&quot;r1.C&quot;</span>)</a></code></pre></div>
<pre><code>## [1] 56</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" title="1"><span class="kw">roundX</span>(<span class="fl">55.55</span>, <span class="dv">1</span>, <span class="st">&quot;r1.C&quot;</span>)</a></code></pre></div>
<pre><code>## [1] 55.5</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb31-1" title="1"><span class="kw">roundX</span>(<span class="fl">55.555</span>, <span class="dv">2</span>, <span class="st">&quot;r1.C&quot;</span>)</a></code></pre></div>
<pre><code>## [1] 55.55</code></pre>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" title="1"><span class="kw">roundX</span>(<span class="fl">55.5555</span>, <span class="dv">3</span>, <span class="st">&quot;r1.C&quot;</span>)</a></code></pre></div>
<pre><code>## [1] 55.556</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb35-1" title="1"><span class="kw">roundX</span>(<span class="fl">55.55555</span>, <span class="dv">4</span>, <span class="st">&quot;r1.C&quot;</span>)</a></code></pre></div>
<pre><code>## [1] 55.5555</code></pre>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb37-1" title="1"><span class="kw">roundX</span>(<span class="fl">55.555555</span>, <span class="dv">5</span>, <span class="st">&quot;r1.C&quot;</span>)</a></code></pre></div>
<pre><code>## [1] 55.55555</code></pre>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb39-1" title="1"><span class="kw">roundX</span>(<span class="fl">55.5555555</span>, <span class="dv">6</span>, <span class="st">&quot;r1.C&quot;</span>)</a></code></pre></div>
<pre><code>## [1] 55.555555</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb41-1" title="1"><span class="kw">roundX</span>(<span class="fl">55.55555555</span>, <span class="dv">7</span>, <span class="st">&quot;r1.C&quot;</span>)</a></code></pre></div>
<pre><code>## [1] 55.5555556</code></pre>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb43-1" title="1"><span class="kw">roundX</span>(<span class="fl">55.555555555</span>, <span class="dv">8</span>, <span class="st">&quot;r1.C&quot;</span>)</a></code></pre></div>
<pre><code>## [1] 55.55555555</code></pre>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb45-1" title="1"><span class="kw">roundX</span>(<span class="fl">55.5555555555</span>, <span class="dv">9</span>, <span class="st">&quot;r1.C&quot;</span>)</a></code></pre></div>
<pre><code>## [1] 55.555555555</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" title="1"><span class="kw">roundX</span>(<span class="fl">55.55555555555</span>,<span class="dv">10</span>, <span class="st">&quot;r1.C&quot;</span>)</a></code></pre></div>
<pre><code>## [1] 55.5555555556</code></pre>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb49-1" title="1"><span class="kw">roundX</span>(<span class="fl">55.555555555555</span>,<span class="dv">11</span>, <span class="st">&quot;r1.C&quot;</span>)</a></code></pre></div>
<pre><code>## [1] 55.55555555556</code></pre>
<p>He used his own C code, to see what happens in R’s C code for <code>round()</code> and proposed to simplify the C code, not doing offset calculations which substract the integer part <code>intx</code>, round and re-add <code>intx</code>. I’ve committed a version of his proposal to R-devel (<code>svn r77609</code>, on 2019-12-21) but found that the simplification improved the above examples in that it always rounded to even, but it clearly broke cases that were working correctly in R 3.6.x. That version is available with our <code>roundX(*, version = &quot;r0.C&quot;)</code> (Version <code>0</code> as it is even simpler than version <code>1</code>).</p>
<p>One CRAN package had relied on <code>round(x, digits = .Machine$integer.max)</code> to return integers unchanged, but</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" title="1"><span class="kw">roundX</span>(<span class="kw">c</span>(<span class="op">-</span><span class="dv">2</span>,<span class="dv">2</span>), <span class="dt">digits =</span> .Machine<span class="op">$</span>integer.max, <span class="dt">version =</span> <span class="st">&quot;r0.C&quot;</span>) <span class="co"># non-sense</span></a></code></pre></div>
<pre><code>## [1] -Inf  Inf</code></pre>
<p>and there were less extreme cases of relatively large <code>digits</code> had stopped working with “r0”. Here, showing two <code>roundX()</code> versions via simple wrapper <code>roundAll()</code>:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" title="1">i &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="op">*</span><span class="st"> </span><span class="dv">2</span><span class="op">^</span>(<span class="dv">33</span><span class="op">:</span><span class="dv">16</span>)</a>
<a class="sourceLine" id="cb53-2" title="2"><span class="kw">stopifnot</span>(i <span class="op">==</span><span class="st"> </span><span class="kw">floor</span>(i)) <span class="co"># are integer valued</span></a>
<a class="sourceLine" id="cb53-3" title="3"><span class="kw">roundAll</span>(i, <span class="dt">digits =</span> <span class="dv">300</span>, <span class="dt">versions =</span> <span class="kw">c</span>(<span class="st">&quot;r0.C&quot;</span>, <span class="st">&quot;r1.C&quot;</span>))</a></code></pre></div>
<pre><code>##             r0.C        r1.C
##  [1,]       -Inf -8589934592
##  [2,]        Inf  4294967296
##  [3,]       -Inf -2147483648
##  [4,]        Inf  1073741824
##  [5,]       -Inf  -536870912
##  [6,]        Inf   268435456
##  [7,] -134217728  -134217728
##  [8,]   67108864    67108864
##  [9,]  -33554432   -33554432
## [10,]   16777216    16777216
## [11,]   -8388608    -8388608
## [12,]    4194304     4194304
## [13,]   -2097152    -2097152
## [14,]    1048576     1048576
## [15,]    -524288     -524288
## [16,]     262144      262144
## [17,]    -131072     -131072
## [18,]      65536       65536</code></pre>
<p>Looking at these, I also found that internally, R’s round had done <code>digits &lt;- pmin(308, digits)</code>, i.e., truncated digits larger than 308 which is clearly not good enough for very small numbers (in absolute value),</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb55-1" title="1">e &lt;-<span class="st"> </span><span class="fl">5.555555555555555555555e-308</span></a>
<a class="sourceLine" id="cb55-2" title="2">d &lt;-<span class="st"> </span><span class="dv">312</span><span class="op">:</span><span class="dv">305</span> ; <span class="kw">names</span>(d) &lt;-<span class="st"> </span><span class="kw">paste0</span>(<span class="st">&quot;d=&quot;</span>, d)</a>
<a class="sourceLine" id="cb55-3" title="3"><span class="kw">roundAll</span>(e, d, <span class="dt">versions =</span> <span class="kw">c</span>(<span class="st">&quot;r0.C&quot;</span>, <span class="st">&quot;r1.C&quot;</span>, <span class="st">&quot;r2.C&quot;</span>))</a></code></pre></div>
<pre><code>##         r0.C   r1.C        r2.C
## d=312 6e-308 6e-308 5.5556e-308
## d=311 6e-308 6e-308 5.5560e-308
## d=310 6e-308 6e-308 5.5600e-308
## d=309 6e-308 6e-308 5.6000e-308
## d=308 6e-308 6e-308 6.0000e-308
## d=307 1e-307 1e-307 1.0000e-307
## d=306  0e+00  0e+00  0.0000e+00
## d=305  0e+00  0e+00  0.0000e+00</code></pre>
<p>As I was embarrassed to have blundered, I’ve worked and committed what now corresponds to <code>roundX(*, version = &quot;r2.C&quot;)</code> to R-devel (<code>svn r77618</code>, on 2019-12-24, 16:11).</p>
<p>Also, Jeroen Ooms, maintainer of CRAN package <code>jsonlite</code>, contacted the CRAN team and me about the change in R-devel which broke one regression test of that package, and on Dec 27, he noticed that R 3.6.2’s version of <code>round()</code> was compatible with the (C library dependent) versions of <code>sprintf()</code> and also with R’s <code>format()</code> whereas the R-devel versions where not, for his example:</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb57-1" title="1">x &lt;-<span class="st"> </span><span class="fl">9.18665</span></a>
<a class="sourceLine" id="cb57-2" title="2"><span class="kw">format</span>(x, <span class="dt">digits =</span> <span class="dv">5</span>) <span class="co">#  &quot;9.1867&quot;</span></a></code></pre></div>
<pre><code>## [1] &quot;9.1867&quot;</code></pre>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb59-1" title="1"><span class="kw">sprintf</span>(<span class="st">&quot;%.4f&quot;</span>, x)    <span class="co">#  &quot;9.1867&quot;</span></a></code></pre></div>
<pre><code>## [1] &quot;9.1867&quot;</code></pre>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb61-1" title="1"><span class="co">## but -- showing now</span></a>
<a class="sourceLine" id="cb61-2" title="2"><span class="kw">roundAll</span>(x, <span class="dv">4</span>)</a></code></pre></div>
<pre><code>## sprintf    r0.C    r1.C   r1a.C    r2.C   r2a.C    r3.C   r3d.C      r3 
##  9.1867  9.1866  9.1867  9.1867  9.1866  9.1866  9.1866  9.1866  9.1866</code></pre>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb63-1" title="1"><span class="co">## but note that</span></a>
<a class="sourceLine" id="cb63-2" title="2"><span class="kw">print</span>(x, <span class="dt">digits=</span><span class="dv">18</span>)</a></code></pre></div>
<pre><code>## [1] 9.1866500000000002</code></pre>
<p>which (typically) shows <code>9.1866500000000002</code>, i.e., a number closer to 9.1867 than to 9.1866, and so really should be rounded up, not down. However, that is partly wrong: Whereas it is true that it’s closer to 9.1867 than to 9.1866, one must be aware that these two decimal numbers are <strong>neither</strong> exactly representable in binary double precision, and a further careful look shows actually the double precision version of these rounded numbers do have the exact same distance to <code>x</code> and that the main principle <em>round to nearest</em> here gives a tie:</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb65-1" title="1"><span class="kw">print</span>(<span class="kw">rbind</span>(<span class="fl">9.1866</span>, <span class="fl">9.18665</span>, <span class="fl">9.1867</span>), <span class="dt">digits=</span><span class="dv">18</span>)</a></code></pre></div>
<pre><code>##                     [,1]
## [1,] 9.18660000000000032
## [2,] 9.18665000000000020
## [3,] 9.18670000000000009</code></pre>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb67-1" title="1"><span class="kw">options</span>(<span class="dt">digits=</span><span class="dv">7</span>) <span class="co"># revert to default</span></a>
<a class="sourceLine" id="cb67-2" title="2">(dx &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">9.1866</span>, <span class="fl">9.1867</span>) <span class="op">-</span><span class="st"> </span>x) <span class="co"># [1] -4.99999999998835e-05  4.99999999998835e-05</span></a></code></pre></div>
<pre><code>## [1] -5e-05  5e-05</code></pre>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb69-1" title="1"><span class="kw">diff</span>(<span class="kw">abs</span>(dx)) <span class="co"># is zero !</span></a></code></pre></div>
<pre><code>## [1] 0</code></pre>
<p>and because of the tie, the <em>round to even</em> rule must apply which means rounding <em>down</em> to 9.1866, and so both libc’s printf and hence R’s <code>sprintf()</code> are as wrong as R 3.6.x has been, and indeed all our <code>roundX()</code> versions apart from <code>&quot;sprintf&quot;</code> and the ’&quot;r1*&quot;’ (previous R) ones, do round down:</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb71-1" title="1"><span class="kw">roundAll</span>(x, <span class="dv">4</span>)</a></code></pre></div>
<pre><code>## sprintf    r0.C    r1.C   r1a.C    r2.C   r2a.C    r3.C   r3d.C      r3 
##  9.1867  9.1866  9.1867  9.1867  9.1866  9.1866  9.1866  9.1866  9.1866</code></pre>
<p>Finally, I think we’ve seen the light and on one hand recalled what we have known for long (but most R users will not be aware of at all)</p>
<blockquote>
<ol style="list-style-type: decimal">
<li>Almost all finite decimal fractions are <strong>not</strong> (exactly) representable as binary double precision numbers,</li>
</ol>
</blockquote>
<p>and consequently,</p>
<blockquote>
<ol start="2" style="list-style-type: decimal">
<li><em>round to nearest</em> applies much more often <em>directly</em> rather than via the tie breaking rule <em>round to even</em> even for the case where the decimal fraction ends in a <code>5</code>.</li>
</ol>
</blockquote>
<p>and hence, a <em>“correct”</em> implementation must really <em>measure, not guess</em> which of the two possible decimals is closer to <code>x</code>. This lead to our R level algorithm <code>round_r3()</code> which is the workhorse used by <code>roundX(x,d, version = &quot;r3&quot;)</code> :</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb73-1" title="1">round_r3</a></code></pre></div>
<pre><code>## function (x, d, info = FALSE, check = TRUE) 
## {
##     if (check) 
##         stopifnot(!anyNA(d), length(d) == 1L)
##     max10e &lt;- 308L
##     if (d &gt; +max10e + 15L) 
##         return(x)
##     else if (d &lt; -max10e) 
##         return(0 * x)
##     p10 &lt;- 10^d
##     x10 &lt;- as.vector(p10 * x)
##     xd &lt;- (i10 &lt;- floor(x10))/p10
##     xu &lt;- ceiling(x10)/p10
##     D &lt;- (xu - x) - (x - xd)
##     e &lt;- i10%%2
##     r &lt;- x
##     i &lt;- (D &lt; 0) | (e &amp; (D == 0))
##     r[i] &lt;- xu[i]
##     r[!i] &lt;- xd[!i]
##     if (info) 
##         list(r = r, D = D, e = e)
##     else r
## }
## &lt;bytecode: 0xa832e58&gt;
## &lt;environment: namespace:round&gt;</code></pre>
<p>and it’s two C level versions <code>&quot;r3.C&quot;</code> (using <code>long double</code>) and <code>&quot;r3d.C&quot;</code> (<em>“d”</em> for <em>“double”</em>, as it uses double precision only).</p>
<p>My current proposal is to use (the equivalent of) <code>&quot;r3d.C&quot;</code> for R 4.0.0, i.e. from April 2020, as not using <code>long double</code> and being very close to the R level implementation <code>&quot;r3&quot;</code> (i.e., <code>round_r3()</code>) renders it potentially less platform dependent and easier to explain and document.</p>
<p>Lastly, note that the original set of examples is then treated differently from all previous proposals:</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb75-1" title="1">                                op &lt;-<span class="st"> </span><span class="kw">options</span>(<span class="dt">digits =</span> <span class="dv">15</span>, <span class="dt">width =</span> <span class="dv">2</span><span class="op">*</span><span class="dv">3</span><span class="op">*</span><span class="dv">23</span>)</a>
<a class="sourceLine" id="cb75-2" title="2"><span class="kw">roundAll</span>(<span class="fl">55.5</span>, <span class="dv">0</span>)</a></code></pre></div>
<pre><code>## sprintf    r0.C    r1.C   r1a.C    r2.C   r2a.C    r3.C   r3d.C      r3 
##      56      56      56      56      56      56      56      56      56</code></pre>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb77-1" title="1"><span class="kw">roundAll</span>(<span class="fl">55.55</span>, <span class="dv">1</span>)</a></code></pre></div>
<pre><code>## sprintf    r0.C    r1.C   r1a.C    r2.C   r2a.C    r3.C   r3d.C      r3 
##    55.5    55.6    55.5    55.5    55.6    55.6    55.5    55.5    55.5</code></pre>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb79-1" title="1"><span class="kw">roundAll</span>(<span class="fl">55.555</span>, <span class="dv">2</span>)</a></code></pre></div>
<pre><code>## sprintf    r0.C    r1.C   r1a.C    r2.C   r2a.C    r3.C   r3d.C      r3 
##   55.55   55.56   55.55   55.55   55.56   55.56   55.56   55.56   55.56</code></pre>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb81-1" title="1"><span class="kw">roundAll</span>(<span class="fl">55.5555</span>, <span class="dv">3</span>)</a></code></pre></div>
<pre><code>## sprintf    r0.C    r1.C   r1a.C    r2.C   r2a.C    r3.C   r3d.C      r3 
##  55.556  55.556  55.556  55.556  55.556  55.556  55.556  55.556  55.556</code></pre>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb83-1" title="1"><span class="kw">roundAll</span>(<span class="fl">55.55555</span>, <span class="dv">4</span>)</a></code></pre></div>
<pre><code>## sprintf    r0.C    r1.C   r1a.C    r2.C   r2a.C    r3.C   r3d.C      r3 
## 55.5555 55.5556 55.5555 55.5555 55.5556 55.5556 55.5555 55.5555 55.5555</code></pre>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb85-1" title="1"><span class="kw">roundAll</span>(<span class="fl">55.555555</span>, <span class="dv">5</span>)</a></code></pre></div>
<pre><code>##  sprintf     r0.C     r1.C    r1a.C     r2.C    r2a.C     r3.C    r3d.C       r3 
## 55.55555 55.55556 55.55555 55.55555 55.55556 55.55556 55.55556 55.55556 55.55556</code></pre>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb87-1" title="1"><span class="kw">roundAll</span>(<span class="fl">55.5555555</span>, <span class="dv">6</span>)</a></code></pre></div>
<pre><code>##   sprintf      r0.C      r1.C     r1a.C      r2.C     r2a.C      r3.C     r3d.C        r3 
## 55.555555 55.555556 55.555555 55.555555 55.555556 55.555556 55.555555 55.555555 55.555555</code></pre>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb89-1" title="1"><span class="kw">roundAll</span>(<span class="fl">55.55555555</span>, <span class="dv">7</span>)</a></code></pre></div>
<pre><code>##    sprintf       r0.C       r1.C      r1a.C       r2.C      r2a.C       r3.C      r3d.C         r3 
## 55.5555556 55.5555556 55.5555556 55.5555556 55.5555556 55.5555556 55.5555556 55.5555556 55.5555556</code></pre>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb91-1" title="1"><span class="kw">roundAll</span>(<span class="fl">55.555555555</span>, <span class="dv">8</span>)</a></code></pre></div>
<pre><code>##     sprintf        r0.C        r1.C       r1a.C        r2.C       r2a.C        r3.C       r3d.C          r3 
## 55.55555555 55.55555556 55.55555555 55.55555555 55.55555556 55.55555556 55.55555555 55.55555555 55.55555555</code></pre>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb93-1" title="1"><span class="kw">roundAll</span>(<span class="fl">55.5555555555</span>, <span class="dv">9</span>)</a></code></pre></div>
<pre><code>##      sprintf         r0.C         r1.C        r1a.C         r2.C        r2a.C         r3.C        r3d.C           r3 
## 55.555555555 55.555555556 55.555555555 55.555555555 55.555555556 55.555555556 55.555555556 55.555555556 55.555555556</code></pre>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb95-1" title="1"><span class="kw">roundAll</span>(<span class="fl">55.55555555555</span>,<span class="dv">10</span>)</a></code></pre></div>
<pre><code>##       sprintf          r0.C          r1.C         r1a.C          r2.C         r2a.C          r3.C         r3d.C            r3 
## 55.5555555556 55.5555555556 55.5555555556 55.5555555556 55.5555555556 55.5555555556 55.5555555556 55.5555555556 55.5555555556</code></pre>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb97-1" title="1"><span class="kw">roundAll</span>(<span class="fl">55.555555555555</span>,<span class="dv">11</span>);   <span class="kw">options</span>(op)</a></code></pre></div>
<pre><code>##        sprintf           r0.C           r1.C          r1a.C           r2.C          r2a.C           r3.C          r3d.C             r3 
## 55.55555555556 55.55555555556 55.55555555556 55.55555555556 55.55555555556 55.55555555556 55.55555555556 55.55555555556 55.55555555556</code></pre>
<div id="session-information" class="section level3">
<h3>Session information</h3>
<pre><code>## R version 3.6.2 Patched (2019-12-14 r77587)
## Platform: x86_64-pc-linux-gnu (64-bit)
## Running under: Fedora 30 (Thirty)
## 
## Matrix products: default
## BLAS:   /u/maechler/R/D/r-patched/F30-64-inst/lib/libRblas.so
## LAPACK: /u/maechler/R/D/r-patched/F30-64-inst/lib/libRlapack.so
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] round_0.12-1
## 
## loaded via a namespace (and not attached):
##  [1] compiler_3.6.2  magrittr_1.5    htmltools_0.4.0 tools_3.6.2    
##  [5] yaml_2.2.0      Rcpp_1.0.3      stringi_1.4.4   rmarkdown_2.0  
##  [9] knitr_1.26      stringr_1.4.0   digest_0.6.23   xfun_0.12      
## [13] rlang_0.4.2     evaluate_0.14</code></pre>
</div>
</div>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
